[tools]
bun = "latest"
gh = "latest"

[tasks.setup]
run = ["bun i"]
dir = "{{ config_root }}/scripts"

[tasks."install:swift"]
run_windows = ['bun run scripts/install-vs.ts', '''
winget install --id Swift.Toolchain -e
''']

[tasks.run]
run = ["swift run"]
dir = "{{ config_root }}/app"

[tasks.build]
run = ["swift build"]
dir = "{{ config_root }}/app"

[tasks.clean]
run = ["swift package clean"]
dir = "{{ config_root }}/app"
